/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visuales.coordinador.Secciones;

import Clases.Estudiante;
import Visuales.administrador.admin_main;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemaintranet.SistemaIntranet;

/**
 *
 * @author Monica
 */
public class CrearSalon extends javax.swing.JFrame {

    SistemaIntranet sistema;
    public CrearSalon() {
        initComponents();
        this.setTitle("Crear secciones");
        this.setLocation(400, 190);
        sistema=new SistemaIntranet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxUniversidad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        JTextNombreSeccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbTurno = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnosDisponibles = new javax.swing.JTable();
        BtnAgregarEstudianteASeccion = new javax.swing.JButton();
        jBtnEliminarEstudianteDeSeccion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlumnosEnLaSeccion = new javax.swing.JTable();
        jBtnCancelarRegistro = new javax.swing.JButton();
        jBtnFinalizarRegistro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnGuardarNombre = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("AGREGAR SECCION");

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        jComboBoxUniversidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UNMSM", "UNAC", "UNI", "UNFV" }));
        jComboBoxUniversidad.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Nueva Sección: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Universidad");

        cmbTurno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde" }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Turno");

        jTableAlumnosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellido"
            }
        ));
        jTableAlumnosDisponibles.setShowGrid(true);
        jScrollPane1.setViewportView(jTableAlumnosDisponibles);

        BtnAgregarEstudianteASeccion.setText("Agregar Estudiante");
        BtnAgregarEstudianteASeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEstudianteASeccionActionPerformed(evt);
            }
        });

        jBtnEliminarEstudianteDeSeccion.setText("Eliminar Estudiante");
        jBtnEliminarEstudianteDeSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarEstudianteDeSeccionActionPerformed(evt);
            }
        });

        jTableAlumnosEnLaSeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Universidad", "Turno"
            }
        ));
        jScrollPane2.setViewportView(jTableAlumnosEnLaSeccion);

        jBtnCancelarRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnCancelarRegistro.setText("Cancelar");
        jBtnCancelarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarRegistroActionPerformed(evt);
            }
        });

        jBtnFinalizarRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnFinalizarRegistro.setText("Acabar Registro");
        jBtnFinalizarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnFinalizarRegistroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setText("Inscritos en:");

        jBtnGuardarNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jBtnGuardarNombre.setText("Guardar Nombre");
        jBtnGuardarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(BtnAgregarEstudianteASeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnEliminarEstudianteDeSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(59, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBtnFinalizarRegistro)
                                .addGap(58, 58, 58))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBtnCancelarRegistro)
                                .addGap(88, 88, 88))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTextNombreSeccion)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxUniversidad, javax.swing.GroupLayout.Alignment.TRAILING, 0, 92, Short.MAX_VALUE)
                                    .addComponent(cmbTurno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnGuardarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(JTextNombreSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jBtnGuardarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jBtnCancelarRegistro)
                        .addGap(38, 38, 38)
                        .addComponent(jBtnFinalizarRegistro))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAgregarEstudianteASeccion)
                    .addComponent(jBtnEliminarEstudianteDeSeccion))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEliminarEstudianteDeSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarEstudianteDeSeccionActionPerformed
        int filaSeleccionada = jTableAlumnosEnLaSeccion.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un estudiante para eliminar de la sección.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener el modelo de la tabla de la sección
        DefaultTableModel modeloSeccion = (DefaultTableModel) jTableAlumnosEnLaSeccion.getModel();
        DefaultTableModel modeloDisponibles = (DefaultTableModel) jTableAlumnosDisponibles.getModel();

        // Obtener los datos del estudiante seleccionado
        String codigo = modeloSeccion.getValueAt(filaSeleccionada, 0).toString();
        String nombre = modeloSeccion.getValueAt(filaSeleccionada, 1).toString();
        String apellido = modeloSeccion.getValueAt(filaSeleccionada, 2).toString();

        // Buscar al estudiante en la lista del sistema y limpiar su atributo de sección
        for (Estudiante est : sistema.getListaEstudiantes()) {
            if (est.getCodigo().equals(codigo)) {
                est.setSeccion(""); // Eliminar la sección asignada al estudiante
                break;
            }
        }

        // Agregar al estudiante de vuelta a la tabla de disponibles
        modeloDisponibles.addRow(new Object[]{codigo, nombre, apellido});

        // Eliminar al estudiante de la tabla de la sección
        modeloSeccion.removeRow(filaSeleccionada);

        JOptionPane.showMessageDialog(this, "Estudiante eliminado de la sección correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBtnEliminarEstudianteDeSeccionActionPerformed

    private void jBtnCancelarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarRegistroActionPerformed
        JOptionPane.showMessageDialog(this, "Has cancelado la operación", 
                "Aviso", JOptionPane.INFORMATION_MESSAGE);
       
    }//GEN-LAST:event_jBtnCancelarRegistroActionPerformed

    private void jBtnFinalizarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnFinalizarRegistroActionPerformed
        String nombreSeccion = JTextNombreSeccion.getText().trim();
        if (nombreSeccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No se puede finalizar el registro sin un nombre de sección.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Guardar el nombre de la sección en el objeto organizador
        sistema.getOrganizador().getSecciones().add(nombreSeccion);

        // Habilitar los campos y botones
        JTextNombreSeccion.setEnabled(true);
        jComboBoxUniversidad.setEnabled(true);
        cmbTurno.setEnabled(true);

        // Limpiar las tablas
        DefaultTableModel modeloDisponibles = (DefaultTableModel) jTableAlumnosDisponibles.getModel();
        modeloDisponibles.setRowCount(0);

        DefaultTableModel modeloSeccion = (DefaultTableModel) jTableAlumnosEnLaSeccion.getModel();
        modeloSeccion.setRowCount(0);

        // Limpiar los espacios de texto
        JTextNombreSeccion.setText("");
        jLabel4.setText("Inscritos en:"); // Restaurar el texto original del label

        // Mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Registro finalizado con éxito. La sección '" + nombreSeccion + "' ha sido guardada.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBtnFinalizarRegistroActionPerformed

    private void jBtnGuardarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarNombreActionPerformed
        
        
        if (JTextNombreSeccion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la sección no puede estar vacío.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return; // Salir del método si está vacío
        }

        String universidadSeleccionada = jComboBoxUniversidad.getSelectedItem().toString();
        String turnoSeleccionado = cmbTurno.getSelectedItem().toString();

        DefaultTableModel modelo = (DefaultTableModel) jTableAlumnosDisponibles.getModel();
        modelo.setRowCount(0); // Limpiar la tabla antes de agregar nuevos resultados

        // Filtrar estudiantes por universidad, turno y seccion no asignada
        for (Estudiante est : sistema.getListaEstudiantes()) {
            if (est.getUniversidad().equals(universidadSeleccionada) 
                    && est.getTurno().equals(turnoSeleccionado)
                    && (est.getSeccion() == null || est.getSeccion().trim().isEmpty())) {
                // Agregar los estudiantes filtrados a la tabla
                modelo.addRow(new Object[]{est.getCodigo(), est.getNombres(), est.getApellidoP()});
            }
        }

        // Mostrar un mensaje si no se encontró ningún estudiante
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron estudiantes sin sección asignada para la universidad y turno seleccionados.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Estudiantes filtrados según universidad, turno y sin sección asignada.", "Información", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnGuardarNombreActionPerformed

    private void BtnAgregarEstudianteASeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEstudianteASeccionActionPerformed
        String nombreSeccion = JTextNombreSeccion.getText().trim();
        jLabel4.setText("Sección: " + nombreSeccion);
        
        
        
        JTextNombreSeccion.setEnabled(false);
        jComboBoxUniversidad.setEnabled(false);
        cmbTurno.setEnabled(false);

        // Validar que haya un estudiante seleccionado
        int filaSeleccionada = jTableAlumnosDisponibles.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un estudiante para agregar a la sección.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener el modelo de las tablas
        DefaultTableModel modeloDisponibles = (DefaultTableModel) jTableAlumnosDisponibles.getModel();
        DefaultTableModel modeloSeccion = (DefaultTableModel) jTableAlumnosEnLaSeccion.getModel();

        // Obtener datos del estudiante seleccionado
        String codigo = modeloDisponibles.getValueAt(filaSeleccionada, 0).toString();
        String nombre = modeloDisponibles.getValueAt(filaSeleccionada, 1).toString();
        String apellido = modeloDisponibles.getValueAt(filaSeleccionada, 2).toString();

        // Buscar al estudiante en la lista y asignar la sección
        
        String universidad = jComboBoxUniversidad.getSelectedItem().toString(); // Universidad seleccionada
        String turno = cmbTurno.getSelectedItem().toString(); // Turno seleccionado

        for (Estudiante est : sistema.getListaEstudiantes()) {
            if (est.getCodigo().equals(codigo)) {
                est.setSeccion(nombreSeccion); // Asignar el nombre de la sección al estudiante
                break;
            }
        }

        // Agregar estudiante con todos sus datos a la tabla de la sección
        modeloSeccion.addRow(new Object[]{codigo, nombre, apellido, universidad, turno});

        // Eliminar el estudiante de la tabla de disponibles
        modeloDisponibles.removeRow(filaSeleccionada);

        JOptionPane.showMessageDialog(this, "Estudiante agregado a la sección correctamente.", "Información", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_BtnAgregarEstudianteASeccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearSalon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearSalon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarEstudianteASeccion;
    private javax.swing.JTextField JTextNombreSeccion;
    private javax.swing.JComboBox<String> cmbTurno;
    private javax.swing.JButton jBtnCancelarRegistro;
    private javax.swing.JButton jBtnEliminarEstudianteDeSeccion;
    private javax.swing.JButton jBtnFinalizarRegistro;
    private javax.swing.JButton jBtnGuardarNombre;
    private javax.swing.JComboBox<String> jComboBoxUniversidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAlumnosDisponibles;
    private javax.swing.JTable jTableAlumnosEnLaSeccion;
    // End of variables declaration//GEN-END:variables
}
